export const INITIAL_CANDIDATES = [
  {
    id: 'c-101',
    candidateNumber: '#01',
    name: 'Maya Lin & The Pulse Duo',
    phone: '+1 (555) 234-8901',
    age: 23,
    govtIdType: 'Passport',
    govtIdNumber: 'P7829104',
    photo: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=800&q=80',
    category: 'Duo / Contemporary',
    style: 'Contemporary & Lyrical Fusion',
    song: 'Ludovico Einaudi - Experience (Remix)',
    bio: 'Contemporary champions bringing raw emotion, acrobatic lifts, and gravity-defying extensions.'
  },
  {
    id: 'c-102',
    candidateNumber: '#02',
    name: 'Kai "Vortex" Tanaka',
    phone: '+1 (555) 345-6712',
    age: 19,
    govtIdType: 'Driving License',
    govtIdNumber: 'DL-CA-90281',
    photo: 'https://images.unsplash.com/photo-1547153760-18fc86324498?auto=format&fit=crop&w=800&q=80',
    category: 'Solo / Street & Popping',
    style: 'Animation, Popping & Tutting',
    song: 'Apashe - Lord & Master',
    bio: 'Underground street battle icon known for microscopic muscle control, mechanical isolations, and robotic illusion.'
  },
  {
    id: 'c-103',
    candidateNumber: '#03',
    name: 'Sofia Valenciaga',
    phone: '+1 (555) 891-2345',
    age: 26,
    govtIdType: 'Passport',
    govtIdNumber: 'P5549021',
    photo: 'https://images.unsplash.com/photo-1518834107812-67b0b7c58434?auto=format&fit=crop&w=800&q=80',
    category: 'Solo / Latin Ballroom',
    style: 'Salsa Con Fuego & Afro-Cuban Rumba',
    song: 'Marc Anthony - Vivir Mi Vida (Live Edit)',
    bio: 'Internationally recognized ballroom soloist with rapid 180 BPM footwork, fierce spins, and theatrical flair.'
  },
  {
    id: 'c-104',
    candidateNumber: '#04',
    name: 'Nova Syndicate Crew',
    phone: '+1 (555) 678-9012',
    age: 22,
    govtIdType: 'National ID',
    govtIdNumber: 'NID-8819024',
    photo: 'https://images.unsplash.com/photo-1535525153412-5a42439a210d?auto=format&fit=crop&w=800&q=80',
    category: 'Crew / Mega Crew',
    style: 'Urban Hip-Hop & Krump Formations',
    song: 'Kendrick Lamar - DNA (Bass Edit)',
    bio: 'Synchronized explosions, intricate visual wave formations, and chest-thumping energy.'
  },
  {
    id: 'c-105',
    candidateNumber: '#05',
    name: 'Aarav & Priya Sharma',
    phone: '+1 (555) 456-7890',
    age: 25,
    govtIdType: 'Passport',
    govtIdNumber: 'P3301982',
    photo: 'https://images.unsplash.com/photo-1509670811275-79453d576390?auto=format&fit=crop&w=800&q=80',
    category: 'Duo / Semi-Classical',
    style: 'Kathak-Contemporary Synthesis',
    song: 'A.R. Rahman - Jai Ho (Orchestral Reimagining)',
    bio: 'Blending classical Indian chakkars (pirouettes) and storytelling with modern cinematic flow.'
  },
  {
    id: 'c-106',
    candidateNumber: '#06',
    name: 'Elena & Damian Vance',
    phone: '+1 (555) 789-0123',
    age: 29,
    govtIdType: 'Driving License',
    govtIdNumber: 'DL-NY-44810',
    photo: 'https://images.unsplash.com/photo-1545959570-a9446733ec60?auto=format&fit=crop&w=800&q=80',
    category: 'Duo / Argentine Tango',
    style: 'Nuevo Tango Escenario',
    song: 'Astor Piazzolla - Libertango',
    bio: 'Dramatic tango virtuosos featuring breathtaking ganchos, passionate boleos, and razor-sharp synchronicity.'
  },
  {
    id: 'c-107',
    candidateNumber: '#07',
    name: 'Zion "Cyber" Cole',
    phone: '+1 (555) 123-4567',
    age: 21,
    govtIdType: 'National ID',
    govtIdNumber: 'NID-9102831',
    photo: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=800&q=80',
    category: 'Solo / Street & Popping',
    style: 'Cyber Glitch & Krump',
    song: 'Skrillex - Supersonic (VIP)',
    bio: 'Known for high-impact staccato glitching, chest hits, and futuristic freestyle battles.'
  },
  {
    id: 'c-108',
    candidateNumber: '#08',
    name: 'Chloe Monet',
    phone: '+1 (555) 234-5678',
    age: 20,
    govtIdType: 'Passport',
    govtIdNumber: 'P8920194',
    photo: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=800&q=80',
    category: 'Solo / Contemporary',
    style: 'Neoclassical Ballet & Flow',
    song: 'Max Richter - On the Nature of Daylight',
    bio: 'Fluid lines, breathtaking arched balances, and ethereal emotional resonance on stage.'
  },
  {
    id: 'c-109',
    candidateNumber: '#09',
    name: 'K-Pulse Urban Alliance',
    phone: '+1 (555) 345-6789',
    age: 23,
    govtIdType: 'State ID Card',
    govtIdNumber: 'SID-4491023',
    photo: 'https://images.unsplash.com/photo-1524594152303-9fd13543fe6e?auto=format&fit=crop&w=800&q=80',
    category: 'Crew / Mega Crew',
    style: 'Synchronized K-Urban & Waacking',
    song: 'NewJeans - Gods (Stadium Remix)',
    bio: 'Ultra-tight angular geometry, rapid wrist waacks, and laser-precise staging formations.'
  },
  {
    id: 'c-110',
    candidateNumber: '#10',
    name: 'Mateo & Isabella Rossi',
    phone: '+1 (555) 456-7891',
    age: 27,
    govtIdType: 'Passport',
    govtIdNumber: 'P6712903',
    photo: 'https://images.unsplash.com/photo-1546707012-0c9f63da0921?auto=format&fit=crop&w=800&q=80',
    category: 'Duo / Latin Ballroom',
    style: 'Fast Paso Doble & Flamenco Fusion',
    song: 'Rodrigo y Gabriela - Diablo Rojo',
    bio: 'Spanish cape work, rhythmic heel stomps, and intense dramatic confrontation choreography.'
  },
  {
    id: 'c-111',
    candidateNumber: '#11',
    name: 'Amara Diallo',
    phone: '+1 (555) 567-8902',
    age: 24,
    govtIdType: 'Passport',
    govtIdNumber: 'P4401928',
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
    category: 'Solo / Contemporary',
    style: 'Afro-Contemporary & Earth Grounding',
    song: 'Burna Boy - Last Last (Acoustic Strings)',
    bio: 'Deep earthy polyrhythms, organic torso articulations, and soul-stirring ancestral narrative.'
  },
  {
    id: 'c-112',
    candidateNumber: '#12',
    name: 'Leo "Zero-G" Brooks',
    phone: '+1 (555) 678-9013',
    age: 22,
    govtIdType: 'Driving License',
    govtIdNumber: 'DL-IL-55819',
    photo: 'https://images.unsplash.com/photo-1519764622345-23439dd774f7?auto=format&fit=crop&w=800&q=80',
    category: 'Solo / Street & Popping',
    style: 'B-boying, Power Moves & Air Flares',
    song: 'The Prodigy - Breathe (Live Beat)',
    bio: 'One-hand handstand spins, lightning headspins, and frictionless gravity-defying freeze drops.'
  },
  {
    id: 'c-113',
    candidateNumber: '#13',
    name: 'Sora & Haruto Takahashi',
    phone: '+1 (555) 789-0124',
    age: 21,
    govtIdType: 'Passport',
    govtIdNumber: 'P9028192',
    photo: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80',
    category: 'Duo / Contemporary',
    style: 'Japanese Butoh & Contemporary Contact',
    song: 'Ryuichi Sakamoto - Merry Christmas Mr. Lawrence',
    bio: 'Hypnotic weight-sharing, silent partner transitions, and emotional minimalism.'
  },
  {
    id: 'c-114',
    candidateNumber: '#14',
    name: 'Eclipse Stomp Troupe',
    phone: '+1 (555) 890-1235',
    age: 26,
    govtIdType: 'National ID',
    govtIdNumber: 'NID-7728190',
    photo: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=800&q=80',
    category: 'Crew / Mega Crew',
    style: 'Urban Tap, Body Percussion & Stomp',
    song: 'Original Live Acoustic Percussion',
    bio: 'Rhythmic powerhouse commanding stage floor resonance through polyrhythmic acapella foot percussion.'
  },
  {
    id: 'c-115',
    candidateNumber: '#15',
    name: 'Nadia Petrova',
    phone: '+1 (555) 901-2346',
    age: 23,
    govtIdType: 'Passport',
    govtIdNumber: 'P1120938',
    photo: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=800&q=80',
    category: 'Solo / Contemporary',
    style: 'Dynamic Aerial & Acro-Dance',
    song: 'Billie Eilish - What Was I Made For? (Epic Orchestra)',
    bio: 'Seamless integration of acrobatic tumbling and delicate storytelling across floor space.'
  },
  {
    id: 'c-116',
    candidateNumber: '#16',
    name: 'Lucas "Phantom" Silva',
    phone: '+1 (555) 012-3457',
    age: 25,
    govtIdType: 'Driving License',
    govtIdNumber: 'DL-TX-99120',
    photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=800&q=80',
    category: 'Solo / Street & Popping',
    style: 'Tutting, Finger Dexterity & Digits',
    song: 'Daft Punk - Technologic (Glitch Edit)',
    bio: 'World finger-tutting master crafting geometric kaleidoscopic optical illusions in real time.'
  },
  {
    id: 'c-117',
    candidateNumber: '#17',
    name: 'Camila & Diego Morales',
    phone: '+1 (555) 123-4568',
    age: 28,
    govtIdType: 'Passport',
    govtIdNumber: 'P8830192',
    photo: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80',
    category: 'Duo / Latin Ballroom',
    style: 'Speed Salsa & Acrobatic Cabaret',
    song: 'Grupo Niche - Cali Pachanguero',
    bio: 'Dazzling overhead lifts, multi-spin combos at breakneck speed, and radiant charisma.'
  },
  {
    id: 'c-118',
    candidateNumber: '#18',
    name: 'Tasha "Vibe" Jenkins',
    phone: '+1 (555) 234-5679',
    age: 22,
    govtIdType: 'State ID Card',
    govtIdNumber: 'SID-6629104',
    photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=800&q=80',
    category: 'Solo / Street & Popping',
    style: 'Commercial Jazz Funk & Heels',
    song: 'Beyoncé - Move (Club Mix)',
    bio: 'High-octane commercial stage presence, razor-sharp lines, and relentless crowd-rousing energy.'
  },
  {
    id: 'c-119',
    candidateNumber: '#19',
    name: 'Ananya Roy',
    phone: '+1 (555) 345-6780',
    age: 24,
    govtIdType: 'Passport',
    govtIdNumber: 'P3391028',
    photo: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80',
    category: 'Solo / Semi-Classical',
    style: 'Odissi-Contemporary Abhinaya',
    song: 'Anoushka Shankar - Voice of the Whispering Wind',
    bio: 'Expressive eye dynamics, rhythmic ankle bells (Ghungroo), and sculptural posture transitions.'
  },
  {
    id: 'c-120',
    candidateNumber: '#20',
    name: 'Velocity Step Division',
    phone: '+1 (555) 456-7892',
    age: 21,
    govtIdType: 'National ID',
    govtIdNumber: 'NID-5510293',
    photo: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80',
    category: 'Crew / Mega Crew',
    style: 'Step & Collegiate Precision Drill',
    song: 'Drumline Live - Marching Battle Cry',
    bio: 'Thunderous hand claps, thigh slaps, boots on floor, creating an orchestral wall of sound and discipline.'
  }
];

export const INITIAL_JUDGES = [
  {
    id: 'j-01',
    name: 'Marcus Chen',
    title: 'Chief Adjudicator & Choreography Master',
    email: 'marcus.chen@dancefest.org',
    accessCode: 'JUDGE-MC99',
    password: 'dance2026',
    status: 'active',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    speciality: 'Choreography & Precision'
  },
  {
    id: 'j-02',
    name: 'Elena Rostova',
    title: 'Prima Ballerina & International Technique Critic',
    email: 'elena.rostova@dancefest.org',
    accessCode: 'JUDGE-ER42',
    password: 'dance2026',
    status: 'active',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    speciality: 'Technique & Artistry'
  }
];

export const INITIAL_ROUNDS = [
  {
    id: 'round-1',
    name: 'Round 1: Preliminary Showcase (20 Competitors)',
    description: 'Initial performance round with all 20 competitors evaluated out of 50 by both judges and fan audience voting. Top 10 advance.',
    status: 'active',
    judgeWeightage: 70,
    audienceWeightage: 30,
    isCurrent: true,
    order: 1
  },
  {
    id: 'round-2',
    name: 'Round 2: Grand Finale Championship (Top 10 Finalists)',
    description: 'Championship round for the Top 10 qualified finalists from Round 1. Scored out of 50 by both judges and audience.',
    status: 'pending',
    judgeWeightage: 50,
    audienceWeightage: 50,
    isCurrent: false,
    order: 2
  }
];

export const INITIAL_SCORES = [];
